// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  ApiRouterTypeAdminAuthLoginData,
  ApiRouterTypeAdminAuthLoginErrors,
  ApiRouterTypeAdminAuthLoginResponses,
  ApiRouterTypeAdminAuthRefreshTokenData,
  ApiRouterTypeAdminAuthRefreshTokenErrors,
  ApiRouterTypeAdminAuthRefreshTokenResponses,
  ApiRouterTypeAdminCreateAppConfigData,
  ApiRouterTypeAdminCreateAppConfigErrors,
  ApiRouterTypeAdminCreateAppConfigResponses,
  ApiRouterTypeAdminCreateUserData,
  ApiRouterTypeAdminCreateUserErrors,
  ApiRouterTypeAdminCreateUserResponses,
  ApiRouterTypeAdminDeleteUserData,
  ApiRouterTypeAdminDeleteUserErrors,
  ApiRouterTypeAdminDeleteUserResponses,
  ApiRouterTypeAdminGetStartupConfigData,
  ApiRouterTypeAdminGetStartupConfigErrors,
  ApiRouterTypeAdminGetStartupConfigResponses,
  ApiRouterTypeAdminSearchAppConfigsData,
  ApiRouterTypeAdminSearchAppConfigsErrors,
  ApiRouterTypeAdminSearchAppConfigsResponses,
  ApiRouterTypeAdminSearchUsersData,
  ApiRouterTypeAdminSearchUsersErrors,
  ApiRouterTypeAdminSearchUsersResponses,
  ApiRouterTypeAdminUpdateAppConfigData,
  ApiRouterTypeAdminUpdateAppConfigErrors,
  ApiRouterTypeAdminUpdateAppConfigResponses,
  ApiRouterTypeAuthenticationCreateTotpData,
  ApiRouterTypeAuthenticationCreateTotpErrors,
  ApiRouterTypeAuthenticationCreateTotpResponses,
  ApiRouterTypeAuthenticationRefreshTokenData,
  ApiRouterTypeAuthenticationRefreshTokenErrors,
  ApiRouterTypeAuthenticationRefreshTokenResponses,
  ApiRouterTypeAuthenticationTelegramLoginData,
  ApiRouterTypeAuthenticationTelegramLoginErrors,
  ApiRouterTypeAuthenticationTelegramLoginResponses,
  ApiRouterTypeAuthenticationVerifyTotpData,
  ApiRouterTypeAuthenticationVerifyTotpErrors,
  ApiRouterTypeAuthenticationVerifyTotpResponses,
  ApiRouterTypeBalanceGetBalanceData,
  ApiRouterTypeBalanceGetBalanceErrors,
  ApiRouterTypeBalanceGetBalanceResponses,
  ApiRouterTypeFileCreateFileData,
  ApiRouterTypeFileCreateFileErrors,
  ApiRouterTypeFileCreateFileResponses,
  ApiRouterTypeFileDeleteFileData,
  ApiRouterTypeFileDeleteFileErrors,
  ApiRouterTypeFileDeleteFileResponses,
  ApiRouterTypeFileGetFileData,
  ApiRouterTypeFileGetFileErrors,
  ApiRouterTypeFileGetFileResponses,
  ApiRouterTypeFileSearchFilesData,
  ApiRouterTypeFileSearchFilesErrors,
  ApiRouterTypeFileSearchFilesResponses,
  ApiRouterTypeFileUpdateFileData,
  ApiRouterTypeFileUpdateFileErrors,
  ApiRouterTypeFileUpdateFileResponses,
  ApiRouterTypeNotificationCreateNotificationData,
  ApiRouterTypeNotificationCreateNotificationErrors,
  ApiRouterTypeNotificationCreateNotificationResponses,
  ApiRouterTypeNotificationDeleteNotificationData,
  ApiRouterTypeNotificationDeleteNotificationErrors,
  ApiRouterTypeNotificationDeleteNotificationResponses,
  ApiRouterTypeNotificationGetNotificationData,
  ApiRouterTypeNotificationGetNotificationErrors,
  ApiRouterTypeNotificationGetNotificationResponses,
  ApiRouterTypeNotificationSearchNotificationsData,
  ApiRouterTypeNotificationSearchNotificationsErrors,
  ApiRouterTypeNotificationSearchNotificationsResponses,
  ApiRouterTypeNotificationUpdateNotificationData,
  ApiRouterTypeNotificationUpdateNotificationErrors,
  ApiRouterTypeNotificationUpdateNotificationResponses,
  ApiRouterTypeNotificationUpdateNotificationStatusData,
  ApiRouterTypeNotificationUpdateNotificationStatusErrors,
  ApiRouterTypeNotificationUpdateNotificationStatusResponses,
  ApiRouterTypePaymentCreatePaymentData,
  ApiRouterTypePaymentCreatePaymentErrors,
  ApiRouterTypePaymentCreatePaymentOccurrenceData,
  ApiRouterTypePaymentCreatePaymentOccurrenceErrors,
  ApiRouterTypePaymentCreatePaymentOccurrenceResponses,
  ApiRouterTypePaymentCreatePaymentResponses,
  ApiRouterTypePaymentDeletePaymentData,
  ApiRouterTypePaymentDeletePaymentErrors,
  ApiRouterTypePaymentDeletePaymentOccurrenceData,
  ApiRouterTypePaymentDeletePaymentOccurrenceErrors,
  ApiRouterTypePaymentDeletePaymentOccurrenceResponses,
  ApiRouterTypePaymentDeletePaymentResponses,
  ApiRouterTypePaymentGetCalendarData,
  ApiRouterTypePaymentGetCalendarErrors,
  ApiRouterTypePaymentGetCalendarResponses,
  ApiRouterTypePaymentGetPaymentData,
  ApiRouterTypePaymentGetPaymentErrors,
  ApiRouterTypePaymentGetPaymentOccurrenceData,
  ApiRouterTypePaymentGetPaymentOccurrenceErrors,
  ApiRouterTypePaymentGetPaymentOccurrenceResponses,
  ApiRouterTypePaymentGetPaymentResponses,
  ApiRouterTypePaymentGetPaymentsWithOccurrencesData,
  ApiRouterTypePaymentGetPaymentsWithOccurrencesErrors,
  ApiRouterTypePaymentGetPaymentsWithOccurrencesResponses,
  ApiRouterTypePaymentGetUpcomingPaymentData,
  ApiRouterTypePaymentGetUpcomingPaymentErrors,
  ApiRouterTypePaymentGetUpcomingPaymentResponses,
  ApiRouterTypePaymentSearchPaymentOccurrencesData,
  ApiRouterTypePaymentSearchPaymentOccurrencesErrors,
  ApiRouterTypePaymentSearchPaymentOccurrencesResponses,
  ApiRouterTypePaymentSearchPaymentsData,
  ApiRouterTypePaymentSearchPaymentsErrors,
  ApiRouterTypePaymentSearchPaymentsResponses,
  ApiRouterTypePaymentUpdatePaymentData,
  ApiRouterTypePaymentUpdatePaymentErrors,
  ApiRouterTypePaymentUpdatePaymentOccurrenceData,
  ApiRouterTypePaymentUpdatePaymentOccurrenceErrors,
  ApiRouterTypePaymentUpdatePaymentOccurrenceResponses,
  ApiRouterTypePaymentUpdatePaymentResponses,
  ApiRouterTypeReferralCreateReferralData,
  ApiRouterTypeReferralCreateReferralErrors,
  ApiRouterTypeReferralCreateReferralResponses,
  ApiRouterTypeReferralDeleteReferralData,
  ApiRouterTypeReferralDeleteReferralErrors,
  ApiRouterTypeReferralDeleteReferralResponses,
  ApiRouterTypeReferralGetReferralData,
  ApiRouterTypeReferralGetReferralErrors,
  ApiRouterTypeReferralGetReferralResponses,
  ApiRouterTypeReferralSearchReferralsData,
  ApiRouterTypeReferralSearchReferralsErrors,
  ApiRouterTypeReferralSearchReferralsResponses,
  ApiRouterTypeReferralUpdateReferralData,
  ApiRouterTypeReferralUpdateReferralErrors,
  ApiRouterTypeReferralUpdateReferralResponses,
  ApiRouterTypeUserGetUserData,
  ApiRouterTypeUserGetUserErrors,
  ApiRouterTypeUserGetUserResponses,
  ApiRouterTypeUserUpdateUserData,
  ApiRouterTypeUserUpdateUserErrors,
  ApiRouterTypeUserUpdateUserResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Create Totp
 */
export const apiRouterTypeAuthenticationCreateTotp = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeAuthenticationCreateTotpData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiRouterTypeAuthenticationCreateTotpResponses,
    ApiRouterTypeAuthenticationCreateTotpErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/auth/create-totp",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Verify Totp
 */
export const apiRouterTypeAuthenticationVerifyTotp = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeAuthenticationVerifyTotpData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiRouterTypeAuthenticationVerifyTotpResponses,
    ApiRouterTypeAuthenticationVerifyTotpErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/auth/verify-totp",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Refresh Token
 */
export const apiRouterTypeAuthenticationRefreshToken = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeAuthenticationRefreshTokenData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiRouterTypeAuthenticationRefreshTokenResponses,
    ApiRouterTypeAuthenticationRefreshTokenErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/auth/refresh-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Telegram Login
 */
export const apiRouterTypeAuthenticationTelegramLogin = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeAuthenticationTelegramLoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiRouterTypeAuthenticationTelegramLoginResponses,
    ApiRouterTypeAuthenticationTelegramLoginErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/auth/telegram-login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get User
 */
export const apiRouterTypeUserGetUser = <ThrowOnError extends boolean = false>(
  options: Options<ApiRouterTypeUserGetUserData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ApiRouterTypeUserGetUserResponses,
    ApiRouterTypeUserGetUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}",
    ...options,
  });

/**
 * Update User
 */
export const apiRouterTypeUserUpdateUser = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeUserUpdateUserData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    ApiRouterTypeUserUpdateUserResponses,
    ApiRouterTypeUserUpdateUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Search Payments
 */
export const apiRouterTypePaymentSearchPayments = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypePaymentSearchPaymentsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ApiRouterTypePaymentSearchPaymentsResponses,
    ApiRouterTypePaymentSearchPaymentsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/payments",
    ...options,
  });

/**
 * Create Payment
 */
export const apiRouterTypePaymentCreatePayment = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypePaymentCreatePaymentData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiRouterTypePaymentCreatePaymentResponses,
    ApiRouterTypePaymentCreatePaymentErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/payments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Payment
 */
export const apiRouterTypePaymentDeletePayment = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypePaymentDeletePaymentData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    ApiRouterTypePaymentDeletePaymentResponses,
    ApiRouterTypePaymentDeletePaymentErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/payments/{payment_uuid}",
    ...options,
  });

/**
 * Get Payment
 */
export const apiRouterTypePaymentGetPayment = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypePaymentGetPaymentData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ApiRouterTypePaymentGetPaymentResponses,
    ApiRouterTypePaymentGetPaymentErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/payments/{payment_uuid}",
    ...options,
  });

/**
 * Update Payment
 */
export const apiRouterTypePaymentUpdatePayment = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypePaymentUpdatePaymentData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    ApiRouterTypePaymentUpdatePaymentResponses,
    ApiRouterTypePaymentUpdatePaymentErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/payments/{payment_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Search Payment Occurrences
 */
export const apiRouterTypePaymentSearchPaymentOccurrences = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ApiRouterTypePaymentSearchPaymentOccurrencesData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    ApiRouterTypePaymentSearchPaymentOccurrencesResponses,
    ApiRouterTypePaymentSearchPaymentOccurrencesErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/payment-occurrences",
    ...options,
  });

/**
 * Create Payment Occurrence
 */
export const apiRouterTypePaymentCreatePaymentOccurrence = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ApiRouterTypePaymentCreatePaymentOccurrenceData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    ApiRouterTypePaymentCreatePaymentOccurrenceResponses,
    ApiRouterTypePaymentCreatePaymentOccurrenceErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/payment-occurrences",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Payment Occurrence
 */
export const apiRouterTypePaymentDeletePaymentOccurrence = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ApiRouterTypePaymentDeletePaymentOccurrenceData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    ApiRouterTypePaymentDeletePaymentOccurrenceResponses,
    ApiRouterTypePaymentDeletePaymentOccurrenceErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/payment-occurrences/{payment_occurrence_uuid}",
    ...options,
  });

/**
 * Get Payment Occurrence
 */
export const apiRouterTypePaymentGetPaymentOccurrence = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypePaymentGetPaymentOccurrenceData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ApiRouterTypePaymentGetPaymentOccurrenceResponses,
    ApiRouterTypePaymentGetPaymentOccurrenceErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/payment-occurrences/{payment_occurrence_uuid}",
    ...options,
  });

/**
 * Update Payment Occurrence
 */
export const apiRouterTypePaymentUpdatePaymentOccurrence = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ApiRouterTypePaymentUpdatePaymentOccurrenceData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).put<
    ApiRouterTypePaymentUpdatePaymentOccurrenceResponses,
    ApiRouterTypePaymentUpdatePaymentOccurrenceErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/payment-occurrences/{payment_occurrence_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Calendar
 */
export const apiRouterTypePaymentGetCalendar = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypePaymentGetCalendarData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ApiRouterTypePaymentGetCalendarResponses,
    ApiRouterTypePaymentGetCalendarErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/calendar",
    ...options,
  });

/**
 * Get Upcoming Payment
 */
export const apiRouterTypePaymentGetUpcomingPayment = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypePaymentGetUpcomingPaymentData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ApiRouterTypePaymentGetUpcomingPaymentResponses,
    ApiRouterTypePaymentGetUpcomingPaymentErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/upcoming-payment",
    ...options,
  });

/**
 * Get Payments With Occurrences
 */
export const apiRouterTypePaymentGetPaymentsWithOccurrences = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ApiRouterTypePaymentGetPaymentsWithOccurrencesData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    ApiRouterTypePaymentGetPaymentsWithOccurrencesResponses,
    ApiRouterTypePaymentGetPaymentsWithOccurrencesErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/payments-with-occurrences",
    ...options,
  });

/**
 * Get Balance
 */
export const apiRouterTypeBalanceGetBalance = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeBalanceGetBalanceData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ApiRouterTypeBalanceGetBalanceResponses,
    ApiRouterTypeBalanceGetBalanceErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/balance",
    ...options,
  });

/**
 * Search Notifications
 */
export const apiRouterTypeNotificationSearchNotifications = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ApiRouterTypeNotificationSearchNotificationsData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    ApiRouterTypeNotificationSearchNotificationsResponses,
    ApiRouterTypeNotificationSearchNotificationsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/notifications",
    ...options,
  });

/**
 * Create Notification
 */
export const apiRouterTypeNotificationCreateNotification = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ApiRouterTypeNotificationCreateNotificationData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    ApiRouterTypeNotificationCreateNotificationResponses,
    ApiRouterTypeNotificationCreateNotificationErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/notifications",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Notification
 */
export const apiRouterTypeNotificationDeleteNotification = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ApiRouterTypeNotificationDeleteNotificationData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    ApiRouterTypeNotificationDeleteNotificationResponses,
    ApiRouterTypeNotificationDeleteNotificationErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/notifications/{notification_uuid}",
    ...options,
  });

/**
 * Get Notification
 */
export const apiRouterTypeNotificationGetNotification = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeNotificationGetNotificationData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ApiRouterTypeNotificationGetNotificationResponses,
    ApiRouterTypeNotificationGetNotificationErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/notifications/{notification_uuid}",
    ...options,
  });

/**
 * Update Notification
 */
export const apiRouterTypeNotificationUpdateNotification = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ApiRouterTypeNotificationUpdateNotificationData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).put<
    ApiRouterTypeNotificationUpdateNotificationResponses,
    ApiRouterTypeNotificationUpdateNotificationErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/notifications/{notification_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update Notification Status
 */
export const apiRouterTypeNotificationUpdateNotificationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ApiRouterTypeNotificationUpdateNotificationStatusData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).patch<
    ApiRouterTypeNotificationUpdateNotificationStatusResponses,
    ApiRouterTypeNotificationUpdateNotificationStatusErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/notifications/{notification_uuid}/status",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Startup Config
 */
export const apiRouterTypeAdminGetStartupConfig = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ApiRouterTypeAdminGetStartupConfigData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ApiRouterTypeAdminGetStartupConfigResponses,
    ApiRouterTypeAdminGetStartupConfigErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/configs/startup",
    ...options,
  });

/**
 * Search Users
 */
export const apiRouterTypeAdminSearchUsers = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeAdminSearchUsersData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ApiRouterTypeAdminSearchUsersResponses,
    ApiRouterTypeAdminSearchUsersErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/configs/{user_uuid}/users",
    ...options,
  });

/**
 * Create User
 */
export const apiRouterTypeAdminCreateUser = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeAdminCreateUserData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiRouterTypeAdminCreateUserResponses,
    ApiRouterTypeAdminCreateUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/configs/{user_uuid}/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete User
 */
export const apiRouterTypeAdminDeleteUser = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeAdminDeleteUserData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    ApiRouterTypeAdminDeleteUserResponses,
    ApiRouterTypeAdminDeleteUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/configs/users/{user_uuid}",
    ...options,
  });

/**
 * Search Referrals
 */
export const apiRouterTypeReferralSearchReferrals = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeReferralSearchReferralsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ApiRouterTypeReferralSearchReferralsResponses,
    ApiRouterTypeReferralSearchReferralsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/referrals",
    ...options,
  });

/**
 * Create Referral
 */
export const apiRouterTypeReferralCreateReferral = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeReferralCreateReferralData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiRouterTypeReferralCreateReferralResponses,
    ApiRouterTypeReferralCreateReferralErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/referrals",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Referral
 */
export const apiRouterTypeReferralDeleteReferral = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeReferralDeleteReferralData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    ApiRouterTypeReferralDeleteReferralResponses,
    ApiRouterTypeReferralDeleteReferralErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/referrals/{referral_uuid}",
    ...options,
  });

/**
 * Get Referral
 */
export const apiRouterTypeReferralGetReferral = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeReferralGetReferralData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ApiRouterTypeReferralGetReferralResponses,
    ApiRouterTypeReferralGetReferralErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/referrals/{referral_uuid}",
    ...options,
  });

/**
 * Update Referral
 */
export const apiRouterTypeReferralUpdateReferral = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeReferralUpdateReferralData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    ApiRouterTypeReferralUpdateReferralResponses,
    ApiRouterTypeReferralUpdateReferralErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/referrals/{referral_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Search Files
 */
export const apiRouterTypeFileSearchFiles = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeFileSearchFilesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ApiRouterTypeFileSearchFilesResponses,
    ApiRouterTypeFileSearchFilesErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/files",
    ...options,
  });

/**
 * Create File
 */
export const apiRouterTypeFileCreateFile = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeFileCreateFileData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiRouterTypeFileCreateFileResponses,
    ApiRouterTypeFileCreateFileErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/files",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete File
 */
export const apiRouterTypeFileDeleteFile = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeFileDeleteFileData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    ApiRouterTypeFileDeleteFileResponses,
    ApiRouterTypeFileDeleteFileErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/files/{file_uuid}",
    ...options,
  });

/**
 * Get File
 */
export const apiRouterTypeFileGetFile = <ThrowOnError extends boolean = false>(
  options: Options<ApiRouterTypeFileGetFileData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ApiRouterTypeFileGetFileResponses,
    ApiRouterTypeFileGetFileErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/files/{file_uuid}",
    ...options,
  });

/**
 * Update File
 */
export const apiRouterTypeFileUpdateFile = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeFileUpdateFileData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    ApiRouterTypeFileUpdateFileResponses,
    ApiRouterTypeFileUpdateFileErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_uuid}/files/{file_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Login
 */
export const apiRouterTypeAdminAuthLogin = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ApiRouterTypeAdminAuthLoginData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    ApiRouterTypeAdminAuthLoginResponses,
    ApiRouterTypeAdminAuthLoginErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/auth/admin/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Refresh Token
 */
export const apiRouterTypeAdminAuthRefreshToken = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeAdminAuthRefreshTokenData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiRouterTypeAdminAuthRefreshTokenResponses,
    ApiRouterTypeAdminAuthRefreshTokenErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/auth/admin/refresh-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Search App Configs
 */
export const apiRouterTypeAdminSearchAppConfigs = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ApiRouterTypeAdminSearchAppConfigsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ApiRouterTypeAdminSearchAppConfigsResponses,
    ApiRouterTypeAdminSearchAppConfigsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/app_configs",
    ...options,
  });

/**
 * Create App Config
 */
export const apiRouterTypeAdminCreateAppConfig = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeAdminCreateAppConfigData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ApiRouterTypeAdminCreateAppConfigResponses,
    ApiRouterTypeAdminCreateAppConfigErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/app_configs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update App Config
 */
export const apiRouterTypeAdminUpdateAppConfig = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ApiRouterTypeAdminUpdateAppConfigData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    ApiRouterTypeAdminUpdateAppConfigResponses,
    ApiRouterTypeAdminUpdateAppConfigErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/admin/app_configs/{app_config_uuid}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
