// This file is auto-generated by @hey-api/openapi-ts

import {
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";
import type { AxiosError } from "axios";

import { client } from "../client.gen";
import {
  apiRouterTypeAdminAuthLogin,
  apiRouterTypeAdminAuthRefreshToken,
  apiRouterTypeAdminCreateAppConfig,
  apiRouterTypeAdminCreateUser,
  apiRouterTypeAdminDeleteUser,
  apiRouterTypeAdminGetStartupConfig,
  apiRouterTypeAdminSearchAppConfigs,
  apiRouterTypeAdminSearchUsers,
  apiRouterTypeAdminUpdateAppConfig,
  apiRouterTypeAuthenticationCreateTotp,
  apiRouterTypeAuthenticationRefreshToken,
  apiRouterTypeAuthenticationTelegramLogin,
  apiRouterTypeAuthenticationVerifyTotp,
  apiRouterTypeBalanceGetBalance,
  apiRouterTypeFileCreateFile,
  apiRouterTypeFileDeleteFile,
  apiRouterTypeFileGetFile,
  apiRouterTypeFileSearchFiles,
  apiRouterTypeFileUpdateFile,
  apiRouterTypeNotificationCreateNotification,
  apiRouterTypeNotificationDeleteNotification,
  apiRouterTypeNotificationGetNotification,
  apiRouterTypeNotificationSearchNotifications,
  apiRouterTypeNotificationUpdateNotification,
  apiRouterTypeNotificationUpdateNotificationStatus,
  apiRouterTypePaymentCreatePayment,
  apiRouterTypePaymentCreatePaymentOccurrence,
  apiRouterTypePaymentDeletePayment,
  apiRouterTypePaymentDeletePaymentOccurrence,
  apiRouterTypePaymentGetCalendar,
  apiRouterTypePaymentGetPayment,
  apiRouterTypePaymentGetPaymentOccurrence,
  apiRouterTypePaymentGetPaymentsWithOccurrences,
  apiRouterTypePaymentGetUpcomingPayment,
  apiRouterTypePaymentSearchPaymentOccurrences,
  apiRouterTypePaymentSearchPayments,
  apiRouterTypePaymentUpdatePayment,
  apiRouterTypePaymentUpdatePaymentOccurrence,
  apiRouterTypeReferralCreateReferral,
  apiRouterTypeReferralDeleteReferral,
  apiRouterTypeReferralGetReferral,
  apiRouterTypeReferralSearchReferrals,
  apiRouterTypeReferralUpdateReferral,
  apiRouterTypeUserGetUser,
  apiRouterTypeUserUpdateUser,
  type Options,
} from "../sdk.gen";
import type {
  ApiRouterTypeAdminAuthLoginData,
  ApiRouterTypeAdminAuthLoginError,
  ApiRouterTypeAdminAuthLoginResponse,
  ApiRouterTypeAdminAuthRefreshTokenData,
  ApiRouterTypeAdminAuthRefreshTokenError,
  ApiRouterTypeAdminAuthRefreshTokenResponse,
  ApiRouterTypeAdminCreateAppConfigData,
  ApiRouterTypeAdminCreateAppConfigError,
  ApiRouterTypeAdminCreateAppConfigResponse,
  ApiRouterTypeAdminCreateUserData,
  ApiRouterTypeAdminCreateUserError,
  ApiRouterTypeAdminCreateUserResponse,
  ApiRouterTypeAdminDeleteUserData,
  ApiRouterTypeAdminDeleteUserError,
  ApiRouterTypeAdminGetStartupConfigData,
  ApiRouterTypeAdminGetStartupConfigError,
  ApiRouterTypeAdminGetStartupConfigResponse,
  ApiRouterTypeAdminSearchAppConfigsData,
  ApiRouterTypeAdminSearchAppConfigsError,
  ApiRouterTypeAdminSearchAppConfigsResponse,
  ApiRouterTypeAdminSearchUsersData,
  ApiRouterTypeAdminSearchUsersError,
  ApiRouterTypeAdminSearchUsersResponse,
  ApiRouterTypeAdminUpdateAppConfigData,
  ApiRouterTypeAdminUpdateAppConfigError,
  ApiRouterTypeAuthenticationCreateTotpData,
  ApiRouterTypeAuthenticationCreateTotpError,
  ApiRouterTypeAuthenticationCreateTotpResponse,
  ApiRouterTypeAuthenticationRefreshTokenData,
  ApiRouterTypeAuthenticationRefreshTokenError,
  ApiRouterTypeAuthenticationRefreshTokenResponse,
  ApiRouterTypeAuthenticationTelegramLoginData,
  ApiRouterTypeAuthenticationTelegramLoginError,
  ApiRouterTypeAuthenticationTelegramLoginResponse,
  ApiRouterTypeAuthenticationVerifyTotpData,
  ApiRouterTypeAuthenticationVerifyTotpError,
  ApiRouterTypeAuthenticationVerifyTotpResponse,
  ApiRouterTypeBalanceGetBalanceData,
  ApiRouterTypeBalanceGetBalanceError,
  ApiRouterTypeBalanceGetBalanceResponse,
  ApiRouterTypeFileCreateFileData,
  ApiRouterTypeFileCreateFileError,
  ApiRouterTypeFileCreateFileResponse,
  ApiRouterTypeFileDeleteFileData,
  ApiRouterTypeFileDeleteFileError,
  ApiRouterTypeFileGetFileData,
  ApiRouterTypeFileGetFileError,
  ApiRouterTypeFileGetFileResponse,
  ApiRouterTypeFileSearchFilesData,
  ApiRouterTypeFileSearchFilesError,
  ApiRouterTypeFileSearchFilesResponse,
  ApiRouterTypeFileUpdateFileData,
  ApiRouterTypeFileUpdateFileError,
  ApiRouterTypeNotificationCreateNotificationData,
  ApiRouterTypeNotificationCreateNotificationError,
  ApiRouterTypeNotificationCreateNotificationResponse,
  ApiRouterTypeNotificationDeleteNotificationData,
  ApiRouterTypeNotificationDeleteNotificationError,
  ApiRouterTypeNotificationGetNotificationData,
  ApiRouterTypeNotificationGetNotificationError,
  ApiRouterTypeNotificationGetNotificationResponse,
  ApiRouterTypeNotificationSearchNotificationsData,
  ApiRouterTypeNotificationSearchNotificationsError,
  ApiRouterTypeNotificationSearchNotificationsResponse,
  ApiRouterTypeNotificationUpdateNotificationData,
  ApiRouterTypeNotificationUpdateNotificationError,
  ApiRouterTypeNotificationUpdateNotificationStatusData,
  ApiRouterTypeNotificationUpdateNotificationStatusError,
  ApiRouterTypePaymentCreatePaymentData,
  ApiRouterTypePaymentCreatePaymentError,
  ApiRouterTypePaymentCreatePaymentOccurrenceData,
  ApiRouterTypePaymentCreatePaymentOccurrenceError,
  ApiRouterTypePaymentCreatePaymentOccurrenceResponse,
  ApiRouterTypePaymentCreatePaymentResponse,
  ApiRouterTypePaymentDeletePaymentData,
  ApiRouterTypePaymentDeletePaymentError,
  ApiRouterTypePaymentDeletePaymentOccurrenceData,
  ApiRouterTypePaymentDeletePaymentOccurrenceError,
  ApiRouterTypePaymentGetCalendarData,
  ApiRouterTypePaymentGetCalendarError,
  ApiRouterTypePaymentGetCalendarResponse,
  ApiRouterTypePaymentGetPaymentData,
  ApiRouterTypePaymentGetPaymentError,
  ApiRouterTypePaymentGetPaymentOccurrenceData,
  ApiRouterTypePaymentGetPaymentOccurrenceError,
  ApiRouterTypePaymentGetPaymentOccurrenceResponse,
  ApiRouterTypePaymentGetPaymentResponse,
  ApiRouterTypePaymentGetPaymentsWithOccurrencesData,
  ApiRouterTypePaymentGetPaymentsWithOccurrencesError,
  ApiRouterTypePaymentGetPaymentsWithOccurrencesResponse,
  ApiRouterTypePaymentGetUpcomingPaymentData,
  ApiRouterTypePaymentGetUpcomingPaymentError,
  ApiRouterTypePaymentGetUpcomingPaymentResponse,
  ApiRouterTypePaymentSearchPaymentOccurrencesData,
  ApiRouterTypePaymentSearchPaymentOccurrencesError,
  ApiRouterTypePaymentSearchPaymentOccurrencesResponse,
  ApiRouterTypePaymentSearchPaymentsData,
  ApiRouterTypePaymentSearchPaymentsError,
  ApiRouterTypePaymentSearchPaymentsResponse,
  ApiRouterTypePaymentUpdatePaymentData,
  ApiRouterTypePaymentUpdatePaymentError,
  ApiRouterTypePaymentUpdatePaymentOccurrenceData,
  ApiRouterTypePaymentUpdatePaymentOccurrenceError,
  ApiRouterTypeReferralCreateReferralData,
  ApiRouterTypeReferralCreateReferralError,
  ApiRouterTypeReferralCreateReferralResponse,
  ApiRouterTypeReferralDeleteReferralData,
  ApiRouterTypeReferralDeleteReferralError,
  ApiRouterTypeReferralGetReferralData,
  ApiRouterTypeReferralGetReferralError,
  ApiRouterTypeReferralGetReferralResponse,
  ApiRouterTypeReferralSearchReferralsData,
  ApiRouterTypeReferralSearchReferralsError,
  ApiRouterTypeReferralSearchReferralsResponse,
  ApiRouterTypeReferralUpdateReferralData,
  ApiRouterTypeReferralUpdateReferralError,
  ApiRouterTypeUserGetUserData,
  ApiRouterTypeUserGetUserError,
  ApiRouterTypeUserGetUserResponse,
  ApiRouterTypeUserUpdateUserData,
  ApiRouterTypeUserUpdateUserError,
} from "../types.gen";

/**
 * Create Totp
 */
export const apiRouterTypeAuthenticationCreateTotpMutation = (
  options?: Partial<Options<ApiRouterTypeAuthenticationCreateTotpData>>,
): UseMutationOptions<
  ApiRouterTypeAuthenticationCreateTotpResponse,
  AxiosError<ApiRouterTypeAuthenticationCreateTotpError>,
  Options<ApiRouterTypeAuthenticationCreateTotpData>
> => {
  const mutationOptions: UseMutationOptions<
    ApiRouterTypeAuthenticationCreateTotpResponse,
    AxiosError<ApiRouterTypeAuthenticationCreateTotpError>,
    Options<ApiRouterTypeAuthenticationCreateTotpData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeAuthenticationCreateTotp({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Verify Totp
 */
export const apiRouterTypeAuthenticationVerifyTotpMutation = (
  options?: Partial<Options<ApiRouterTypeAuthenticationVerifyTotpData>>,
): UseMutationOptions<
  ApiRouterTypeAuthenticationVerifyTotpResponse,
  AxiosError<ApiRouterTypeAuthenticationVerifyTotpError>,
  Options<ApiRouterTypeAuthenticationVerifyTotpData>
> => {
  const mutationOptions: UseMutationOptions<
    ApiRouterTypeAuthenticationVerifyTotpResponse,
    AxiosError<ApiRouterTypeAuthenticationVerifyTotpError>,
    Options<ApiRouterTypeAuthenticationVerifyTotpData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeAuthenticationVerifyTotp({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Refresh Token
 */
export const apiRouterTypeAuthenticationRefreshTokenMutation = (
  options?: Partial<Options<ApiRouterTypeAuthenticationRefreshTokenData>>,
): UseMutationOptions<
  ApiRouterTypeAuthenticationRefreshTokenResponse,
  AxiosError<ApiRouterTypeAuthenticationRefreshTokenError>,
  Options<ApiRouterTypeAuthenticationRefreshTokenData>
> => {
  const mutationOptions: UseMutationOptions<
    ApiRouterTypeAuthenticationRefreshTokenResponse,
    AxiosError<ApiRouterTypeAuthenticationRefreshTokenError>,
    Options<ApiRouterTypeAuthenticationRefreshTokenData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeAuthenticationRefreshToken({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Telegram Login
 */
export const apiRouterTypeAuthenticationTelegramLoginMutation = (
  options?: Partial<Options<ApiRouterTypeAuthenticationTelegramLoginData>>,
): UseMutationOptions<
  ApiRouterTypeAuthenticationTelegramLoginResponse,
  AxiosError<ApiRouterTypeAuthenticationTelegramLoginError>,
  Options<ApiRouterTypeAuthenticationTelegramLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    ApiRouterTypeAuthenticationTelegramLoginResponse,
    AxiosError<ApiRouterTypeAuthenticationTelegramLoginError>,
    Options<ApiRouterTypeAuthenticationTelegramLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeAuthenticationTelegramLogin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL:
      options?.baseURL || (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const apiRouterTypeUserGetUserQueryKey = (
  options: Options<ApiRouterTypeUserGetUserData>,
) => createQueryKey("apiRouterTypeUserGetUser", options);

/**
 * Get User
 */
export const apiRouterTypeUserGetUserOptions = (
  options: Options<ApiRouterTypeUserGetUserData>,
) =>
  queryOptions<
    ApiRouterTypeUserGetUserResponse,
    AxiosError<ApiRouterTypeUserGetUserError>,
    ApiRouterTypeUserGetUserResponse,
    ReturnType<typeof apiRouterTypeUserGetUserQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await apiRouterTypeUserGetUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: apiRouterTypeUserGetUserQueryKey(options),
  });

/**
 * Update User
 */
export const apiRouterTypeUserUpdateUserMutation = (
  options?: Partial<Options<ApiRouterTypeUserUpdateUserData>>,
): UseMutationOptions<
  unknown,
  AxiosError<ApiRouterTypeUserUpdateUserError>,
  Options<ApiRouterTypeUserUpdateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<ApiRouterTypeUserUpdateUserError>,
    Options<ApiRouterTypeUserUpdateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeUserUpdateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const apiRouterTypePaymentSearchPaymentsQueryKey = (
  options: Options<ApiRouterTypePaymentSearchPaymentsData>,
) => createQueryKey("apiRouterTypePaymentSearchPayments", options);

/**
 * Search Payments
 */
export const apiRouterTypePaymentSearchPaymentsOptions = (
  options: Options<ApiRouterTypePaymentSearchPaymentsData>,
) =>
  queryOptions<
    ApiRouterTypePaymentSearchPaymentsResponse,
    AxiosError<ApiRouterTypePaymentSearchPaymentsError>,
    ApiRouterTypePaymentSearchPaymentsResponse,
    ReturnType<typeof apiRouterTypePaymentSearchPaymentsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await apiRouterTypePaymentSearchPayments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: apiRouterTypePaymentSearchPaymentsQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const apiRouterTypePaymentSearchPaymentsInfiniteQueryKey = (
  options: Options<ApiRouterTypePaymentSearchPaymentsData>,
): QueryKey<Options<ApiRouterTypePaymentSearchPaymentsData>> =>
  createQueryKey("apiRouterTypePaymentSearchPayments", options, true);

/**
 * Search Payments
 */
export const apiRouterTypePaymentSearchPaymentsInfiniteOptions = (
  options: Options<ApiRouterTypePaymentSearchPaymentsData>,
) =>
  infiniteQueryOptions<
    ApiRouterTypePaymentSearchPaymentsResponse,
    AxiosError<ApiRouterTypePaymentSearchPaymentsError>,
    InfiniteData<ApiRouterTypePaymentSearchPaymentsResponse>,
    QueryKey<Options<ApiRouterTypePaymentSearchPaymentsData>>,
    | number
    | Pick<
        QueryKey<Options<ApiRouterTypePaymentSearchPaymentsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-expect-error sfdsfsd
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-expect-error sfdsfsd

        const page: Pick<
          QueryKey<Options<ApiRouterTypePaymentSearchPaymentsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await apiRouterTypePaymentSearchPayments({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: apiRouterTypePaymentSearchPaymentsInfiniteQueryKey(options),
    },
  );

/**
 * Create Payment
 */
export const apiRouterTypePaymentCreatePaymentMutation = (
  options?: Partial<Options<ApiRouterTypePaymentCreatePaymentData>>,
): UseMutationOptions<
  ApiRouterTypePaymentCreatePaymentResponse,
  AxiosError<ApiRouterTypePaymentCreatePaymentError>,
  Options<ApiRouterTypePaymentCreatePaymentData>
> => {
  const mutationOptions: UseMutationOptions<
    ApiRouterTypePaymentCreatePaymentResponse,
    AxiosError<ApiRouterTypePaymentCreatePaymentError>,
    Options<ApiRouterTypePaymentCreatePaymentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypePaymentCreatePayment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Payment
 */
export const apiRouterTypePaymentDeletePaymentMutation = (
  options?: Partial<Options<ApiRouterTypePaymentDeletePaymentData>>,
): UseMutationOptions<
  unknown,
  AxiosError<ApiRouterTypePaymentDeletePaymentError>,
  Options<ApiRouterTypePaymentDeletePaymentData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<ApiRouterTypePaymentDeletePaymentError>,
    Options<ApiRouterTypePaymentDeletePaymentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypePaymentDeletePayment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const apiRouterTypePaymentGetPaymentQueryKey = (
  options: Options<ApiRouterTypePaymentGetPaymentData>,
) => createQueryKey("apiRouterTypePaymentGetPayment", options);

/**
 * Get Payment
 */
export const apiRouterTypePaymentGetPaymentOptions = (
  options: Options<ApiRouterTypePaymentGetPaymentData>,
) =>
  queryOptions<
    ApiRouterTypePaymentGetPaymentResponse,
    AxiosError<ApiRouterTypePaymentGetPaymentError>,
    ApiRouterTypePaymentGetPaymentResponse,
    ReturnType<typeof apiRouterTypePaymentGetPaymentQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await apiRouterTypePaymentGetPayment({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: apiRouterTypePaymentGetPaymentQueryKey(options),
  });

/**
 * Update Payment
 */
export const apiRouterTypePaymentUpdatePaymentMutation = (
  options?: Partial<Options<ApiRouterTypePaymentUpdatePaymentData>>,
): UseMutationOptions<
  unknown,
  AxiosError<ApiRouterTypePaymentUpdatePaymentError>,
  Options<ApiRouterTypePaymentUpdatePaymentData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<ApiRouterTypePaymentUpdatePaymentError>,
    Options<ApiRouterTypePaymentUpdatePaymentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypePaymentUpdatePayment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const apiRouterTypePaymentSearchPaymentOccurrencesQueryKey = (
  options: Options<ApiRouterTypePaymentSearchPaymentOccurrencesData>,
) => createQueryKey("apiRouterTypePaymentSearchPaymentOccurrences", options);

/**
 * Search Payment Occurrences
 */
export const apiRouterTypePaymentSearchPaymentOccurrencesOptions = (
  options: Options<ApiRouterTypePaymentSearchPaymentOccurrencesData>,
) =>
  queryOptions<
    ApiRouterTypePaymentSearchPaymentOccurrencesResponse,
    AxiosError<ApiRouterTypePaymentSearchPaymentOccurrencesError>,
    ApiRouterTypePaymentSearchPaymentOccurrencesResponse,
    ReturnType<typeof apiRouterTypePaymentSearchPaymentOccurrencesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await apiRouterTypePaymentSearchPaymentOccurrences({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: apiRouterTypePaymentSearchPaymentOccurrencesQueryKey(options),
  });

export const apiRouterTypePaymentSearchPaymentOccurrencesInfiniteQueryKey = (
  options: Options<ApiRouterTypePaymentSearchPaymentOccurrencesData>,
): QueryKey<Options<ApiRouterTypePaymentSearchPaymentOccurrencesData>> =>
  createQueryKey("apiRouterTypePaymentSearchPaymentOccurrences", options, true);

/**
 * Search Payment Occurrences
 */
export const apiRouterTypePaymentSearchPaymentOccurrencesInfiniteOptions = (
  options: Options<ApiRouterTypePaymentSearchPaymentOccurrencesData>,
) =>
  infiniteQueryOptions<
    ApiRouterTypePaymentSearchPaymentOccurrencesResponse,
    AxiosError<ApiRouterTypePaymentSearchPaymentOccurrencesError>,
    InfiniteData<ApiRouterTypePaymentSearchPaymentOccurrencesResponse>,
    QueryKey<Options<ApiRouterTypePaymentSearchPaymentOccurrencesData>>,
    | number
    | Pick<
        QueryKey<Options<ApiRouterTypePaymentSearchPaymentOccurrencesData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-expect-error sfdsfsd
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-expect-error sfdsfsd
        const page: Pick<
          QueryKey<
            Options<ApiRouterTypePaymentSearchPaymentOccurrencesData>
          >[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await apiRouterTypePaymentSearchPaymentOccurrences({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey:
        apiRouterTypePaymentSearchPaymentOccurrencesInfiniteQueryKey(options),
    },
  );

/**
 * Create Payment Occurrence
 */
export const apiRouterTypePaymentCreatePaymentOccurrenceMutation = (
  options?: Partial<Options<ApiRouterTypePaymentCreatePaymentOccurrenceData>>,
): UseMutationOptions<
  ApiRouterTypePaymentCreatePaymentOccurrenceResponse,
  AxiosError<ApiRouterTypePaymentCreatePaymentOccurrenceError>,
  Options<ApiRouterTypePaymentCreatePaymentOccurrenceData>
> => {
  const mutationOptions: UseMutationOptions<
    ApiRouterTypePaymentCreatePaymentOccurrenceResponse,
    AxiosError<ApiRouterTypePaymentCreatePaymentOccurrenceError>,
    Options<ApiRouterTypePaymentCreatePaymentOccurrenceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypePaymentCreatePaymentOccurrence({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Payment Occurrence
 */
export const apiRouterTypePaymentDeletePaymentOccurrenceMutation = (
  options?: Partial<Options<ApiRouterTypePaymentDeletePaymentOccurrenceData>>,
): UseMutationOptions<
  unknown,
  AxiosError<ApiRouterTypePaymentDeletePaymentOccurrenceError>,
  Options<ApiRouterTypePaymentDeletePaymentOccurrenceData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<ApiRouterTypePaymentDeletePaymentOccurrenceError>,
    Options<ApiRouterTypePaymentDeletePaymentOccurrenceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypePaymentDeletePaymentOccurrence({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const apiRouterTypePaymentGetPaymentOccurrenceQueryKey = (
  options: Options<ApiRouterTypePaymentGetPaymentOccurrenceData>,
) => createQueryKey("apiRouterTypePaymentGetPaymentOccurrence", options);

/**
 * Get Payment Occurrence
 */
export const apiRouterTypePaymentGetPaymentOccurrenceOptions = (
  options: Options<ApiRouterTypePaymentGetPaymentOccurrenceData>,
) =>
  queryOptions<
    ApiRouterTypePaymentGetPaymentOccurrenceResponse,
    AxiosError<ApiRouterTypePaymentGetPaymentOccurrenceError>,
    ApiRouterTypePaymentGetPaymentOccurrenceResponse,
    ReturnType<typeof apiRouterTypePaymentGetPaymentOccurrenceQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await apiRouterTypePaymentGetPaymentOccurrence({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: apiRouterTypePaymentGetPaymentOccurrenceQueryKey(options),
  });

/**
 * Update Payment Occurrence
 */
export const apiRouterTypePaymentUpdatePaymentOccurrenceMutation = (
  options?: Partial<Options<ApiRouterTypePaymentUpdatePaymentOccurrenceData>>,
): UseMutationOptions<
  unknown,
  AxiosError<ApiRouterTypePaymentUpdatePaymentOccurrenceError>,
  Options<ApiRouterTypePaymentUpdatePaymentOccurrenceData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<ApiRouterTypePaymentUpdatePaymentOccurrenceError>,
    Options<ApiRouterTypePaymentUpdatePaymentOccurrenceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypePaymentUpdatePaymentOccurrence({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const apiRouterTypePaymentGetCalendarQueryKey = (
  options: Options<ApiRouterTypePaymentGetCalendarData>,
) => createQueryKey("apiRouterTypePaymentGetCalendar", options);

/**
 * Get Calendar
 */
export const apiRouterTypePaymentGetCalendarOptions = (
  options: Options<ApiRouterTypePaymentGetCalendarData>,
) =>
  queryOptions<
    ApiRouterTypePaymentGetCalendarResponse,
    AxiosError<ApiRouterTypePaymentGetCalendarError>,
    ApiRouterTypePaymentGetCalendarResponse,
    ReturnType<typeof apiRouterTypePaymentGetCalendarQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await apiRouterTypePaymentGetCalendar({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: apiRouterTypePaymentGetCalendarQueryKey(options),
  });

export const apiRouterTypePaymentGetUpcomingPaymentQueryKey = (
  options: Options<ApiRouterTypePaymentGetUpcomingPaymentData>,
) => createQueryKey("apiRouterTypePaymentGetUpcomingPayment", options);

/**
 * Get Upcoming Payment
 */
export const apiRouterTypePaymentGetUpcomingPaymentOptions = (
  options: Options<ApiRouterTypePaymentGetUpcomingPaymentData>,
) =>
  queryOptions<
    ApiRouterTypePaymentGetUpcomingPaymentResponse,
    AxiosError<ApiRouterTypePaymentGetUpcomingPaymentError>,
    ApiRouterTypePaymentGetUpcomingPaymentResponse,
    ReturnType<typeof apiRouterTypePaymentGetUpcomingPaymentQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await apiRouterTypePaymentGetUpcomingPayment({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: apiRouterTypePaymentGetUpcomingPaymentQueryKey(options),
  });

export const apiRouterTypePaymentGetPaymentsWithOccurrencesQueryKey = (
  options: Options<ApiRouterTypePaymentGetPaymentsWithOccurrencesData>,
) => createQueryKey("apiRouterTypePaymentGetPaymentsWithOccurrences", options);

/**
 * Get Payments With Occurrences
 */
export const apiRouterTypePaymentGetPaymentsWithOccurrencesOptions = (
  options: Options<ApiRouterTypePaymentGetPaymentsWithOccurrencesData>,
) =>
  queryOptions<
    ApiRouterTypePaymentGetPaymentsWithOccurrencesResponse,
    AxiosError<ApiRouterTypePaymentGetPaymentsWithOccurrencesError>,
    ApiRouterTypePaymentGetPaymentsWithOccurrencesResponse,
    ReturnType<typeof apiRouterTypePaymentGetPaymentsWithOccurrencesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await apiRouterTypePaymentGetPaymentsWithOccurrences({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: apiRouterTypePaymentGetPaymentsWithOccurrencesQueryKey(options),
  });

export const apiRouterTypePaymentGetPaymentsWithOccurrencesInfiniteQueryKey = (
  options: Options<ApiRouterTypePaymentGetPaymentsWithOccurrencesData>,
): QueryKey<Options<ApiRouterTypePaymentGetPaymentsWithOccurrencesData>> =>
  createQueryKey(
    "apiRouterTypePaymentGetPaymentsWithOccurrences",
    options,
    true,
  );

/**
 * Get Payments With Occurrences
 */
export const apiRouterTypePaymentGetPaymentsWithOccurrencesInfiniteOptions = (
  options: Options<ApiRouterTypePaymentGetPaymentsWithOccurrencesData>,
) =>
  infiniteQueryOptions<
    ApiRouterTypePaymentGetPaymentsWithOccurrencesResponse,
    AxiosError<ApiRouterTypePaymentGetPaymentsWithOccurrencesError>,
    InfiniteData<ApiRouterTypePaymentGetPaymentsWithOccurrencesResponse>,
    QueryKey<Options<ApiRouterTypePaymentGetPaymentsWithOccurrencesData>>,
    | number
    | Pick<
        QueryKey<
          Options<ApiRouterTypePaymentGetPaymentsWithOccurrencesData>
        >[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-expect-error sfdsfsd
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-expect-error sfdsfsd
        const page: Pick<
          QueryKey<
            Options<ApiRouterTypePaymentGetPaymentsWithOccurrencesData>
          >[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await apiRouterTypePaymentGetPaymentsWithOccurrences({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey:
        apiRouterTypePaymentGetPaymentsWithOccurrencesInfiniteQueryKey(options),
    },
  );

export const apiRouterTypeBalanceGetBalanceQueryKey = (
  options: Options<ApiRouterTypeBalanceGetBalanceData>,
) => createQueryKey("apiRouterTypeBalanceGetBalance", options);

/**
 * Get Balance
 */
export const apiRouterTypeBalanceGetBalanceOptions = (
  options: Options<ApiRouterTypeBalanceGetBalanceData>,
) =>
  queryOptions<
    ApiRouterTypeBalanceGetBalanceResponse,
    AxiosError<ApiRouterTypeBalanceGetBalanceError>,
    ApiRouterTypeBalanceGetBalanceResponse,
    ReturnType<typeof apiRouterTypeBalanceGetBalanceQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await apiRouterTypeBalanceGetBalance({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: apiRouterTypeBalanceGetBalanceQueryKey(options),
  });

export const apiRouterTypeNotificationSearchNotificationsQueryKey = (
  options: Options<ApiRouterTypeNotificationSearchNotificationsData>,
) => createQueryKey("apiRouterTypeNotificationSearchNotifications", options);

/**
 * Search Notifications
 */
export const apiRouterTypeNotificationSearchNotificationsOptions = (
  options: Options<ApiRouterTypeNotificationSearchNotificationsData>,
) =>
  queryOptions<
    ApiRouterTypeNotificationSearchNotificationsResponse,
    AxiosError<ApiRouterTypeNotificationSearchNotificationsError>,
    ApiRouterTypeNotificationSearchNotificationsResponse,
    ReturnType<typeof apiRouterTypeNotificationSearchNotificationsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await apiRouterTypeNotificationSearchNotifications({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: apiRouterTypeNotificationSearchNotificationsQueryKey(options),
  });

export const apiRouterTypeNotificationSearchNotificationsInfiniteQueryKey = (
  options: Options<ApiRouterTypeNotificationSearchNotificationsData>,
): QueryKey<Options<ApiRouterTypeNotificationSearchNotificationsData>> =>
  createQueryKey("apiRouterTypeNotificationSearchNotifications", options, true);

/**
 * Search Notifications
 */
export const apiRouterTypeNotificationSearchNotificationsInfiniteOptions = (
  options: Options<ApiRouterTypeNotificationSearchNotificationsData>,
) =>
  infiniteQueryOptions<
    ApiRouterTypeNotificationSearchNotificationsResponse,
    AxiosError<ApiRouterTypeNotificationSearchNotificationsError>,
    InfiniteData<ApiRouterTypeNotificationSearchNotificationsResponse>,
    QueryKey<Options<ApiRouterTypeNotificationSearchNotificationsData>>,
    | number
    | Pick<
        QueryKey<Options<ApiRouterTypeNotificationSearchNotificationsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-expect-error sfdsfsd
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-expect-error sfdsfsd
        const page: Pick<
          QueryKey<
            Options<ApiRouterTypeNotificationSearchNotificationsData>
          >[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await apiRouterTypeNotificationSearchNotifications({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey:
        apiRouterTypeNotificationSearchNotificationsInfiniteQueryKey(options),
    },
  );

/**
 * Create Notification
 */
export const apiRouterTypeNotificationCreateNotificationMutation = (
  options?: Partial<Options<ApiRouterTypeNotificationCreateNotificationData>>,
): UseMutationOptions<
  ApiRouterTypeNotificationCreateNotificationResponse,
  AxiosError<ApiRouterTypeNotificationCreateNotificationError>,
  Options<ApiRouterTypeNotificationCreateNotificationData>
> => {
  const mutationOptions: UseMutationOptions<
    ApiRouterTypeNotificationCreateNotificationResponse,
    AxiosError<ApiRouterTypeNotificationCreateNotificationError>,
    Options<ApiRouterTypeNotificationCreateNotificationData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeNotificationCreateNotification({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Notification
 */
export const apiRouterTypeNotificationDeleteNotificationMutation = (
  options?: Partial<Options<ApiRouterTypeNotificationDeleteNotificationData>>,
): UseMutationOptions<
  unknown,
  AxiosError<ApiRouterTypeNotificationDeleteNotificationError>,
  Options<ApiRouterTypeNotificationDeleteNotificationData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<ApiRouterTypeNotificationDeleteNotificationError>,
    Options<ApiRouterTypeNotificationDeleteNotificationData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeNotificationDeleteNotification({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const apiRouterTypeNotificationGetNotificationQueryKey = (
  options: Options<ApiRouterTypeNotificationGetNotificationData>,
) => createQueryKey("apiRouterTypeNotificationGetNotification", options);

/**
 * Get Notification
 */
export const apiRouterTypeNotificationGetNotificationOptions = (
  options: Options<ApiRouterTypeNotificationGetNotificationData>,
) =>
  queryOptions<
    ApiRouterTypeNotificationGetNotificationResponse,
    AxiosError<ApiRouterTypeNotificationGetNotificationError>,
    ApiRouterTypeNotificationGetNotificationResponse,
    ReturnType<typeof apiRouterTypeNotificationGetNotificationQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await apiRouterTypeNotificationGetNotification({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: apiRouterTypeNotificationGetNotificationQueryKey(options),
  });

/**
 * Update Notification
 */
export const apiRouterTypeNotificationUpdateNotificationMutation = (
  options?: Partial<Options<ApiRouterTypeNotificationUpdateNotificationData>>,
): UseMutationOptions<
  unknown,
  AxiosError<ApiRouterTypeNotificationUpdateNotificationError>,
  Options<ApiRouterTypeNotificationUpdateNotificationData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<ApiRouterTypeNotificationUpdateNotificationError>,
    Options<ApiRouterTypeNotificationUpdateNotificationData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeNotificationUpdateNotification({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Notification Status
 */
export const apiRouterTypeNotificationUpdateNotificationStatusMutation = (
  options?: Partial<
    Options<ApiRouterTypeNotificationUpdateNotificationStatusData>
  >,
): UseMutationOptions<
  unknown,
  AxiosError<ApiRouterTypeNotificationUpdateNotificationStatusError>,
  Options<ApiRouterTypeNotificationUpdateNotificationStatusData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<ApiRouterTypeNotificationUpdateNotificationStatusError>,
    Options<ApiRouterTypeNotificationUpdateNotificationStatusData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeNotificationUpdateNotificationStatus({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const apiRouterTypeAdminGetStartupConfigQueryKey = (
  options?: Options<ApiRouterTypeAdminGetStartupConfigData>,
) => createQueryKey("apiRouterTypeAdminGetStartupConfig", options);

/**
 * Get Startup Config
 */
export const apiRouterTypeAdminGetStartupConfigOptions = (
  options?: Options<ApiRouterTypeAdminGetStartupConfigData>,
) =>
  queryOptions<
    ApiRouterTypeAdminGetStartupConfigResponse,
    AxiosError<ApiRouterTypeAdminGetStartupConfigError>,
    ApiRouterTypeAdminGetStartupConfigResponse,
    ReturnType<typeof apiRouterTypeAdminGetStartupConfigQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await apiRouterTypeAdminGetStartupConfig({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: apiRouterTypeAdminGetStartupConfigQueryKey(options),
  });

export const apiRouterTypeAdminSearchUsersQueryKey = (
  options: Options<ApiRouterTypeAdminSearchUsersData>,
) => createQueryKey("apiRouterTypeAdminSearchUsers", options);

/**
 * Search Users
 */
export const apiRouterTypeAdminSearchUsersOptions = (
  options: Options<ApiRouterTypeAdminSearchUsersData>,
) =>
  queryOptions<
    ApiRouterTypeAdminSearchUsersResponse,
    AxiosError<ApiRouterTypeAdminSearchUsersError>,
    ApiRouterTypeAdminSearchUsersResponse,
    ReturnType<typeof apiRouterTypeAdminSearchUsersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await apiRouterTypeAdminSearchUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: apiRouterTypeAdminSearchUsersQueryKey(options),
  });

export const apiRouterTypeAdminSearchUsersInfiniteQueryKey = (
  options: Options<ApiRouterTypeAdminSearchUsersData>,
): QueryKey<Options<ApiRouterTypeAdminSearchUsersData>> =>
  createQueryKey("apiRouterTypeAdminSearchUsers", options, true);

/**
 * Search Users
 */
export const apiRouterTypeAdminSearchUsersInfiniteOptions = (
  options: Options<ApiRouterTypeAdminSearchUsersData>,
) =>
  infiniteQueryOptions<
    ApiRouterTypeAdminSearchUsersResponse,
    AxiosError<ApiRouterTypeAdminSearchUsersError>,
    InfiniteData<ApiRouterTypeAdminSearchUsersResponse>,
    QueryKey<Options<ApiRouterTypeAdminSearchUsersData>>,
    | number
    | Pick<
        QueryKey<Options<ApiRouterTypeAdminSearchUsersData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-expect-error sfdsfsd
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-expect-error sfdsfsd
        const page: Pick<
          QueryKey<Options<ApiRouterTypeAdminSearchUsersData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await apiRouterTypeAdminSearchUsers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: apiRouterTypeAdminSearchUsersInfiniteQueryKey(options),
    },
  );

/**
 * Create User
 */
export const apiRouterTypeAdminCreateUserMutation = (
  options?: Partial<Options<ApiRouterTypeAdminCreateUserData>>,
): UseMutationOptions<
  ApiRouterTypeAdminCreateUserResponse,
  AxiosError<ApiRouterTypeAdminCreateUserError>,
  Options<ApiRouterTypeAdminCreateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    ApiRouterTypeAdminCreateUserResponse,
    AxiosError<ApiRouterTypeAdminCreateUserError>,
    Options<ApiRouterTypeAdminCreateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeAdminCreateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete User
 */
export const apiRouterTypeAdminDeleteUserMutation = (
  options?: Partial<Options<ApiRouterTypeAdminDeleteUserData>>,
): UseMutationOptions<
  unknown,
  AxiosError<ApiRouterTypeAdminDeleteUserError>,
  Options<ApiRouterTypeAdminDeleteUserData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<ApiRouterTypeAdminDeleteUserError>,
    Options<ApiRouterTypeAdminDeleteUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeAdminDeleteUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const apiRouterTypeReferralSearchReferralsQueryKey = (
  options: Options<ApiRouterTypeReferralSearchReferralsData>,
) => createQueryKey("apiRouterTypeReferralSearchReferrals", options);

/**
 * Search Referrals
 */
export const apiRouterTypeReferralSearchReferralsOptions = (
  options: Options<ApiRouterTypeReferralSearchReferralsData>,
) =>
  queryOptions<
    ApiRouterTypeReferralSearchReferralsResponse,
    AxiosError<ApiRouterTypeReferralSearchReferralsError>,
    ApiRouterTypeReferralSearchReferralsResponse,
    ReturnType<typeof apiRouterTypeReferralSearchReferralsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await apiRouterTypeReferralSearchReferrals({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: apiRouterTypeReferralSearchReferralsQueryKey(options),
  });

export const apiRouterTypeReferralSearchReferralsInfiniteQueryKey = (
  options: Options<ApiRouterTypeReferralSearchReferralsData>,
): QueryKey<Options<ApiRouterTypeReferralSearchReferralsData>> =>
  createQueryKey("apiRouterTypeReferralSearchReferrals", options, true);

/**
 * Search Referrals
 */
export const apiRouterTypeReferralSearchReferralsInfiniteOptions = (
  options: Options<ApiRouterTypeReferralSearchReferralsData>,
) =>
  infiniteQueryOptions<
    ApiRouterTypeReferralSearchReferralsResponse,
    AxiosError<ApiRouterTypeReferralSearchReferralsError>,
    InfiniteData<ApiRouterTypeReferralSearchReferralsResponse>,
    QueryKey<Options<ApiRouterTypeReferralSearchReferralsData>>,
    | number
    | Pick<
        QueryKey<Options<ApiRouterTypeReferralSearchReferralsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-expect-error sfdsfsd
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-expect-error sfdsfsd
        const page: Pick<
          QueryKey<Options<ApiRouterTypeReferralSearchReferralsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await apiRouterTypeReferralSearchReferrals({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: apiRouterTypeReferralSearchReferralsInfiniteQueryKey(options),
    },
  );

/**
 * Create Referral
 */
export const apiRouterTypeReferralCreateReferralMutation = (
  options?: Partial<Options<ApiRouterTypeReferralCreateReferralData>>,
): UseMutationOptions<
  ApiRouterTypeReferralCreateReferralResponse,
  AxiosError<ApiRouterTypeReferralCreateReferralError>,
  Options<ApiRouterTypeReferralCreateReferralData>
> => {
  const mutationOptions: UseMutationOptions<
    ApiRouterTypeReferralCreateReferralResponse,
    AxiosError<ApiRouterTypeReferralCreateReferralError>,
    Options<ApiRouterTypeReferralCreateReferralData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeReferralCreateReferral({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Referral
 */
export const apiRouterTypeReferralDeleteReferralMutation = (
  options?: Partial<Options<ApiRouterTypeReferralDeleteReferralData>>,
): UseMutationOptions<
  unknown,
  AxiosError<ApiRouterTypeReferralDeleteReferralError>,
  Options<ApiRouterTypeReferralDeleteReferralData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<ApiRouterTypeReferralDeleteReferralError>,
    Options<ApiRouterTypeReferralDeleteReferralData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeReferralDeleteReferral({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const apiRouterTypeReferralGetReferralQueryKey = (
  options: Options<ApiRouterTypeReferralGetReferralData>,
) => createQueryKey("apiRouterTypeReferralGetReferral", options);

/**
 * Get Referral
 */
export const apiRouterTypeReferralGetReferralOptions = (
  options: Options<ApiRouterTypeReferralGetReferralData>,
) =>
  queryOptions<
    ApiRouterTypeReferralGetReferralResponse,
    AxiosError<ApiRouterTypeReferralGetReferralError>,
    ApiRouterTypeReferralGetReferralResponse,
    ReturnType<typeof apiRouterTypeReferralGetReferralQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await apiRouterTypeReferralGetReferral({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: apiRouterTypeReferralGetReferralQueryKey(options),
  });

/**
 * Update Referral
 */
export const apiRouterTypeReferralUpdateReferralMutation = (
  options?: Partial<Options<ApiRouterTypeReferralUpdateReferralData>>,
): UseMutationOptions<
  unknown,
  AxiosError<ApiRouterTypeReferralUpdateReferralError>,
  Options<ApiRouterTypeReferralUpdateReferralData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<ApiRouterTypeReferralUpdateReferralError>,
    Options<ApiRouterTypeReferralUpdateReferralData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeReferralUpdateReferral({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const apiRouterTypeFileSearchFilesQueryKey = (
  options: Options<ApiRouterTypeFileSearchFilesData>,
) => createQueryKey("apiRouterTypeFileSearchFiles", options);

/**
 * Search Files
 */
export const apiRouterTypeFileSearchFilesOptions = (
  options: Options<ApiRouterTypeFileSearchFilesData>,
) =>
  queryOptions<
    ApiRouterTypeFileSearchFilesResponse,
    AxiosError<ApiRouterTypeFileSearchFilesError>,
    ApiRouterTypeFileSearchFilesResponse,
    ReturnType<typeof apiRouterTypeFileSearchFilesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await apiRouterTypeFileSearchFiles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: apiRouterTypeFileSearchFilesQueryKey(options),
  });

export const apiRouterTypeFileSearchFilesInfiniteQueryKey = (
  options: Options<ApiRouterTypeFileSearchFilesData>,
): QueryKey<Options<ApiRouterTypeFileSearchFilesData>> =>
  createQueryKey("apiRouterTypeFileSearchFiles", options, true);

/**
 * Search Files
 */
export const apiRouterTypeFileSearchFilesInfiniteOptions = (
  options: Options<ApiRouterTypeFileSearchFilesData>,
) =>
  infiniteQueryOptions<
    ApiRouterTypeFileSearchFilesResponse,
    AxiosError<ApiRouterTypeFileSearchFilesError>,
    InfiniteData<ApiRouterTypeFileSearchFilesResponse>,
    QueryKey<Options<ApiRouterTypeFileSearchFilesData>>,
    | number
    | Pick<
        QueryKey<Options<ApiRouterTypeFileSearchFilesData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-expect-error sfdsfsd
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-expect-error sfdsfsd
        const page: Pick<
          QueryKey<Options<ApiRouterTypeFileSearchFilesData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await apiRouterTypeFileSearchFiles({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: apiRouterTypeFileSearchFilesInfiniteQueryKey(options),
    },
  );

/**
 * Create File
 */
export const apiRouterTypeFileCreateFileMutation = (
  options?: Partial<Options<ApiRouterTypeFileCreateFileData>>,
): UseMutationOptions<
  ApiRouterTypeFileCreateFileResponse,
  AxiosError<ApiRouterTypeFileCreateFileError>,
  Options<ApiRouterTypeFileCreateFileData>
> => {
  const mutationOptions: UseMutationOptions<
    ApiRouterTypeFileCreateFileResponse,
    AxiosError<ApiRouterTypeFileCreateFileError>,
    Options<ApiRouterTypeFileCreateFileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeFileCreateFile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete File
 */
export const apiRouterTypeFileDeleteFileMutation = (
  options?: Partial<Options<ApiRouterTypeFileDeleteFileData>>,
): UseMutationOptions<
  unknown,
  AxiosError<ApiRouterTypeFileDeleteFileError>,
  Options<ApiRouterTypeFileDeleteFileData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<ApiRouterTypeFileDeleteFileError>,
    Options<ApiRouterTypeFileDeleteFileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeFileDeleteFile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const apiRouterTypeFileGetFileQueryKey = (
  options: Options<ApiRouterTypeFileGetFileData>,
) => createQueryKey("apiRouterTypeFileGetFile", options);

/**
 * Get File
 */
export const apiRouterTypeFileGetFileOptions = (
  options: Options<ApiRouterTypeFileGetFileData>,
) =>
  queryOptions<
    ApiRouterTypeFileGetFileResponse,
    AxiosError<ApiRouterTypeFileGetFileError>,
    ApiRouterTypeFileGetFileResponse,
    ReturnType<typeof apiRouterTypeFileGetFileQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await apiRouterTypeFileGetFile({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: apiRouterTypeFileGetFileQueryKey(options),
  });

/**
 * Update File
 */
export const apiRouterTypeFileUpdateFileMutation = (
  options?: Partial<Options<ApiRouterTypeFileUpdateFileData>>,
): UseMutationOptions<
  unknown,
  AxiosError<ApiRouterTypeFileUpdateFileError>,
  Options<ApiRouterTypeFileUpdateFileData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<ApiRouterTypeFileUpdateFileError>,
    Options<ApiRouterTypeFileUpdateFileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeFileUpdateFile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Login
 */
export const apiRouterTypeAdminAuthLoginMutation = (
  options?: Partial<Options<ApiRouterTypeAdminAuthLoginData>>,
): UseMutationOptions<
  ApiRouterTypeAdminAuthLoginResponse,
  AxiosError<ApiRouterTypeAdminAuthLoginError>,
  Options<ApiRouterTypeAdminAuthLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    ApiRouterTypeAdminAuthLoginResponse,
    AxiosError<ApiRouterTypeAdminAuthLoginError>,
    Options<ApiRouterTypeAdminAuthLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeAdminAuthLogin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Refresh Token
 */
export const apiRouterTypeAdminAuthRefreshTokenMutation = (
  options?: Partial<Options<ApiRouterTypeAdminAuthRefreshTokenData>>,
): UseMutationOptions<
  ApiRouterTypeAdminAuthRefreshTokenResponse,
  AxiosError<ApiRouterTypeAdminAuthRefreshTokenError>,
  Options<ApiRouterTypeAdminAuthRefreshTokenData>
> => {
  const mutationOptions: UseMutationOptions<
    ApiRouterTypeAdminAuthRefreshTokenResponse,
    AxiosError<ApiRouterTypeAdminAuthRefreshTokenError>,
    Options<ApiRouterTypeAdminAuthRefreshTokenData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeAdminAuthRefreshToken({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const apiRouterTypeAdminSearchAppConfigsQueryKey = (
  options?: Options<ApiRouterTypeAdminSearchAppConfigsData>,
) => createQueryKey("apiRouterTypeAdminSearchAppConfigs", options);

/**
 * Search App Configs
 */
export const apiRouterTypeAdminSearchAppConfigsOptions = (
  options?: Options<ApiRouterTypeAdminSearchAppConfigsData>,
) =>
  queryOptions<
    ApiRouterTypeAdminSearchAppConfigsResponse,
    AxiosError<ApiRouterTypeAdminSearchAppConfigsError>,
    ApiRouterTypeAdminSearchAppConfigsResponse,
    ReturnType<typeof apiRouterTypeAdminSearchAppConfigsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await apiRouterTypeAdminSearchAppConfigs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: apiRouterTypeAdminSearchAppConfigsQueryKey(options),
  });

export const apiRouterTypeAdminSearchAppConfigsInfiniteQueryKey = (
  options?: Options<ApiRouterTypeAdminSearchAppConfigsData>,
): QueryKey<Options<ApiRouterTypeAdminSearchAppConfigsData>> =>
  createQueryKey("apiRouterTypeAdminSearchAppConfigs", options, true);

/**
 * Search App Configs
 */
export const apiRouterTypeAdminSearchAppConfigsInfiniteOptions = (
  options?: Options<ApiRouterTypeAdminSearchAppConfigsData>,
) =>
  infiniteQueryOptions<
    ApiRouterTypeAdminSearchAppConfigsResponse,
    AxiosError<ApiRouterTypeAdminSearchAppConfigsError>,
    InfiniteData<ApiRouterTypeAdminSearchAppConfigsResponse>,
    QueryKey<Options<ApiRouterTypeAdminSearchAppConfigsData>>,
    | number
    | Pick<
        QueryKey<Options<ApiRouterTypeAdminSearchAppConfigsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-expect-error sfdsfsd
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        const page: Pick<
          QueryKey<Options<ApiRouterTypeAdminSearchAppConfigsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await apiRouterTypeAdminSearchAppConfigs({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: apiRouterTypeAdminSearchAppConfigsInfiniteQueryKey(options),
    },
  );

/**
 * Create App Config
 */
export const apiRouterTypeAdminCreateAppConfigMutation = (
  options?: Partial<Options<ApiRouterTypeAdminCreateAppConfigData>>,
): UseMutationOptions<
  ApiRouterTypeAdminCreateAppConfigResponse,
  AxiosError<ApiRouterTypeAdminCreateAppConfigError>,
  Options<ApiRouterTypeAdminCreateAppConfigData>
> => {
  const mutationOptions: UseMutationOptions<
    ApiRouterTypeAdminCreateAppConfigResponse,
    AxiosError<ApiRouterTypeAdminCreateAppConfigError>,
    Options<ApiRouterTypeAdminCreateAppConfigData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeAdminCreateAppConfig({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update App Config
 */
export const apiRouterTypeAdminUpdateAppConfigMutation = (
  options?: Partial<Options<ApiRouterTypeAdminUpdateAppConfigData>>,
): UseMutationOptions<
  unknown,
  AxiosError<ApiRouterTypeAdminUpdateAppConfigError>,
  Options<ApiRouterTypeAdminUpdateAppConfigData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<ApiRouterTypeAdminUpdateAppConfigError>,
    Options<ApiRouterTypeAdminUpdateAppConfigData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await apiRouterTypeAdminUpdateAppConfig({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
