import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import Header from "@/features/header/components/Header";
import Footer from "@/features/footer/components/Footer";
import ReduxProvider from "@/features/shared/redux/Provider";
import { QueryProviders } from "@/features/shared/ui/QueryProvider";
import Panel from "@/features/panel/components/Panel";

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirmatn.variable} antialiased bg-bg`}>
        <QueryProviders>
          <ReduxProvider>
            <Header />
            <Panel />
            {children}
            <Footer />
          </ReduxProvider>
        </QueryProviders>
      </body>
    </html>
  );
}
